[package]
name = "doubledown"
version = "0.1.0"
authors = ["sebastian"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lib"
path = "src/lib.rs"

[dependencies]
nom = "5.1.2"
#tectonic = "0.1.15"